spring:
  application:
    name: order-service
  config:
    import: "configserver:http://localhost:19000"
  cloud:
    config:
      name: order-service
      profile: dev
      fail-fast: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: order-service