
spring:
  application:
    name: gateway-service
  config:
    import: "configserver:http://localhost:19000"
  cloud:
    config:
      name: gateway-service
      profile: dev
      fail-fast: true
