server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_manager_db
    username: pathfinder
    password: pathfinder123
  data:
    redis:
      database: 4
  kafka:
    consumer:
      group-id: delivery-manager-service-group

logging:
  level:
    com.pathfinder.delivery_manager: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.kafka: INFO
jwt:
  secret:
    key: c3BhcnRhX3Rpa2l0YWthX2JhcHppcF8xMjM0NTY3ODk=

springdoc:
  api-docs:
    path: /springdoc/openapi3-delivery-manager-service.json