server:
  port: 19200

spring:
  main:
    web-application-type: reactive
  cloud:
    loadbalancer:
      cache:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # User Service Routes
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**, /springdoc/openapi3-user-service.json
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        # Delivery Service Routes
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/deliveries/**, /api/v1/delivery-routes/**, /springdoc/openapi3-delivery-service.json
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        # Hub Service Routes
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/api/v1/hubs/**, /api/v1/hub-routes/**, /springdoc/openapi3-hub-service.json
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        # Delivery Manager Service Routes
        - id: delivery-manager-service
          uri: lb://delivery-manager-service
          predicates:
            - Path=/api/v1/delivery-managers/**, /springdoc/openapi3-delivery-manager-service.json
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        # Order Service Routes
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**, /springdoc/openapi3-order-service.json
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        # Product Service Routes
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**, /springdoc/openapi3-product-service.json
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        # Company Service Routes
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/v1/companies/**, /springdoc/openapi3-company-service.json
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    gateway:
      access: unrestricted
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  swagger-ui:
    urls:
      - name: 0-user-service
        url: /springdoc/openapi3-user-service.json
      - name: 1-delivery-service
        url: /springdoc/openapi3-delivery-service.json
      - name: 2-hub-service
        url: /springdoc/openapi3-hub-service.json
      - name: 3-order-service
        url: /springdoc/openapi3-order-service.json
      - name: 4-delivery-manager-service
        url: /springdoc/openapi3-delivery-manager-service.json
      - name: 5-product-service
        url: /springdoc/openapi3-product-service.json
      - name: 6-company-service
        url: /springdoc/openapi3-company-service.json
    path: /docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 20
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 6000
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 20s
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true
