server:
  port: 8083

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/hub_db
    username: pathfinder
    password: pathfinder123
  data:
    redis:
      database: 2
jwt:
  secret:
    key: c3BhcnRhX3Rpa2l0YWthX2JhcHppcF8xMjM0NTY3ODk=

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  api-docs:
    path: /springdoc/openapi3-hub-service.json