server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: pathfinder
    password: pathfinder123
  redis:
    database: 5
  kafka:
    consumer:
      group-id: product-service

logging:
  level:
    com.pathfinder.product: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cache: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.client: DEBUG
  file:
    name: logs/product-service.log

# External Service URLs
services:
  company-service:
    url: http://localhost:8087
  hub-service:
    url: http://localhost:8083
  user-service:
    url: http://localhost:8081
  order-service:
    url: http://localhost:8084

springdoc:
  api-docs:
    path: /springdoc/openapi3-product-service.json

