spring:
  application:
    name: company-service
  config:
    import: optional:configserver:http://localhost:19000
  cloud:
    config:
      name: company-service
      profile: dev
      fail-fast: false
